[package]
name = "nura-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib"]

[dependencies]
nura-domain = { path = "../nura-domain" }
nura-library = { path = "../nura-library" }
nura-mpv = { path = "../nura-mpv" }
nura-player-core = { path = "../nura-player-core" }
serde_json.workspace = true
